// Copyright 2026 Marc-Antoine Ruel. All Rights Reserved. Use of this
// source code is governed by the Apache v2 license that can be found in the
// LICENSE file.

package methodfilecheck

import (
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

func TestCheck(t *testing.T) {
	t.Run("valid", func(t *testing.T) {
		cases := []struct {
			name  string
			files map[string]string
		}{
			{"methods after type", map[string]string{"a.go": `package p

type Foo struct{}

func (f *Foo) A() {}

func (f *Foo) b() {}
`}},
			{"constructors between type and methods", map[string]string{"a.go": `package p

type Foo struct{}

func NewFoo() (*Foo, error) { return &Foo{}, nil }

func newFoo() Foo { return Foo{} }

func (f *Foo) A() {}
`}},
			{"generic constructor", map[string]string{"a.go": `package p

type Foo[T any] struct{}

func NewFoo[T any]() *Foo[T] { return nil }

func (f *Foo[T]) A() {}
`}},
			{"free helper inside method block", map[string]string{"a.go": `package p

type Foo struct{}

func (f *Foo) A() {}

func helper() {}

func (f *Foo) B() {}
`}},
			{"grouped type decl", map[string]string{"a.go": `package p

type (
	Foo struct{}
	Bar struct{}
)

func (f *Foo) A() {}
`}},
			{"generated file skipped", map[string]string{
				"a.go": `package p

type Foo struct{}

func (f *Foo) A() {}
`,
				"gen.go": `// Code generated by gen DO NOT EDIT.

package p

func helper() {}

func (f *Foo) B() {}
`,
			}},
			{"guarded files not compared", map[string]string{
				"a.go": `//go:build linux

package p

type Foo struct{}
`,
				"b.go": `//go:build windows

package p

func (f *Foo) A() {}
`,
			}},
			{"xtest package separate", map[string]string{
				"a.go": `package p

type Foo struct{}

func (f *Foo) A() {}
`,
				"x_test.go": `package p_test

type Bar struct{}

func (b *Bar) A() {}
`,
			}},
		}
		for _, c := range cases {
			t.Run(c.name, func(t *testing.T) {
				if got := runCheck(t, c.files); len(got) != 0 {
					t.Fatalf("got violations:\n%s", strings.Join(got, "\n"))
				}
			})
		}
	})
	t.Run("error", func(t *testing.T) {
		cases := []struct {
			name  string
			files map[string]string
			want  []string
		}{
			{
				"free function between type and methods",
				map[string]string{"a.go": `package p

type Foo struct{}

func helper() {}

func (f *Foo) A() {}
`},
				[]string{"a.go:7: method Foo.A: type declared at line 3 is separated from its first method; keep the type, its constructors, and its complete method block together"},
			},
			{
				"other type's constructor between type and methods",
				map[string]string{"a.go": `package p

type Foo struct{}

type Bar struct{}

func NewBar() *Bar { return nil }

func (f *Foo) A() {}
`},
				[]string{"a.go:9: method Foo.A: type declared at line 3 is separated from its first method; keep the type, its constructors, and its complete method block together"},
			},
			{
				"method before type",
				map[string]string{"a.go": `package p

func NewFoo() *Foo { return nil }

func (f *Foo) A() {}

type Foo struct{}
`},
				[]string{"a.go:5: method Foo.A: type declared at line 7 is separated from its first method; keep the type, its constructors, and its complete method block together"},
			},
			{
				"method in other file lands after constructors",
				map[string]string{
					"a.go": `package p

type Foo struct{}

func NewFoo() *Foo { return nil }
`,
					"b.go": `package p

func (f *Foo) A() {}
`,
				},
				[]string{"b.go:3: method Foo.A: move after a.go:5 (after Foo declaration and any constructors)"},
			},
			{
				"unexported method in other file lands after whole block",
				map[string]string{
					"a.go": `package p

type Foo struct{}

func (f *Foo) A() {}

func (f *Foo) b() {}
`,
					"b.go": `package p

func (f *Foo) c() {}
`,
				},
				[]string{"b.go:3: method Foo.c: move after a.go:7 (after last Foo method)"},
			},
			{
				"exported method in other file lands after last exported",
				map[string]string{
					"a.go": `package p

type Foo struct{}

func (f *Foo) A() {}

func (f *Foo) B() {}

func (f *Foo) c() {}
`,
					"b.go": `package p

func (f *Foo) D() {}
`,
				},
				[]string{"b.go:3: method Foo.D: move after a.go:7 (after last exported Foo method)"},
			},
			{
				"exported method in other file lands above unexported block",
				map[string]string{
					"a.go": `package p

type Foo struct{}

func (f *Foo) a() {}

func (f *Foo) b() {}
`,
					"b.go": `package p

func (f *Foo) C() {}
`,
				},
				[]string{"b.go:3: method Foo.C: move above a.go:5 (before Foo methods (exported first))"},
			},
			{
				"interleaved receivers",
				map[string]string{"a.go": `package p

type Foo struct{}

func (f *Foo) A() {}

type Bar struct{}

func (b *Bar) A() {}

func (f *Foo) B() {}
`},
				[]string{"a.go:11: method Foo.B: move after a.go:5 to keep Foo methods contiguous"},
			},
			{
				"interleaved exported above unexported run",
				map[string]string{"a.go": `package p

type Foo struct{}

func (f *Foo) a() {}

type Bar struct{}

func (b *Bar) A() {}

func (f *Foo) B() {}
`},
				[]string{"a.go:11: method Foo.B: move above a.go:5 to keep Foo methods contiguous"},
			},
			{
				"constructor between type and methods anchors below it",
				map[string]string{"a.go": `package p

type Foo struct{}

type Bar struct{}

func NewFoo() *Foo { return nil }

func helper() {}

func (f *Foo) A() {}
`},
				[]string{"a.go:11: method Foo.A: type declared at line 3 is separated from its first method; keep the type, its constructors, and its complete method block together"},
			},
			{
				"constructor after methods",
				map[string]string{"a.go": `package p

type Foo struct{}

func (f *Foo) A() {}

func NewFoo() *Foo { return nil }
`},
				[]string{"a.go:7: constructor NewFoo for Foo: move after a.go:3 (before Foo methods)"},
			},
			{
				"every reopening run reported",
				map[string]string{"a.go": `package p

type Foo struct{}

func (f *Foo) A() {}

type Bar struct{}

func (b *Bar) A() {}

func (f *Foo) B() {}

type Baz struct{}

func (z *Baz) A() {}

func (f *Foo) C() {}
`},
				[]string{
					"a.go:11: method Foo.B: move after a.go:5 to keep Foo methods contiguous",
					"a.go:17: method Foo.C: move after a.go:11 to keep Foo methods contiguous",
				},
			},
		}
		for _, c := range cases {
			t.Run(c.name, func(t *testing.T) {
				if got := runCheck(t, c.files); !slices.Equal(got, c.want) {
					t.Fatalf("got:\n%s\nwant:\n%s", strings.Join(got, "\n"), strings.Join(c.want, "\n"))
				}
				// Every reported violation must carry a fix.
				vs, err := Check(pkgFromFiles(t, c.files))
				if err != nil {
					t.Fatal(err)
				}
				for _, v := range vs {
					if v.Fix == nil {
						t.Errorf("%s: no fix", &v)
					}
				}
			})
		}
	})
}

func TestCheckSyntax(t *testing.T) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, filepath.Join(t.TempDir(), "a.go"), `package p

type Foo struct{}

func (f *Foo) A() {}
`, parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}
	if vs := CheckSyntax(fset, []*ast.File{f}); len(vs) != 0 {
		t.Fatalf("got %v", vs)
	}
	// A misplaced method in a generated file is not reported.
	gen, err := parser.ParseFile(fset, filepath.Join(t.TempDir(), "gen.go"), `// Code generated by x DO NOT EDIT.
package p

func (f *Foo) B() {}
`, parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}
	if vs := CheckSyntax(fset, append([]*ast.File{f}, gen)); len(vs) != 0 {
		t.Fatalf("got %v", vs)
	}
}

// runCheck writes files to a temporary package, changes into it so reports use
// relative paths, and returns the report lines.
func runCheck(t *testing.T, files map[string]string) []string {
	t.Helper()
	vs, err := Check(pkgFromFiles(t, files))
	if err != nil {
		t.Fatal(err)
	}
	out := make([]string, len(vs))
	for i, v := range vs {
		out[i] = v.String()
	}
	return out
}

// pkgFromFiles builds a Package description from in-memory sources and
// changes into its directory so reports use relative paths.
func pkgFromFiles(t *testing.T, files map[string]string) Package {
	t.Helper()
	dir := t.TempDir()
	t.Chdir(dir)
	pkg := Package{ImportPath: "p", Dir: dir}
	for name, src := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(src), 0o600); err != nil {
			t.Fatal(err)
		}
		switch {
		case strings.HasSuffix(name, "_test.go") && strings.Contains(src, "package p_test"):
			pkg.XTestGoFiles = append(pkg.XTestGoFiles, name)
		case strings.HasSuffix(name, "_test.go"):
			pkg.TestGoFiles = append(pkg.TestGoFiles, name)
		default:
			pkg.GoFiles = append(pkg.GoFiles, name)
		}
	}
	slices.Sort(pkg.GoFiles)
	slices.Sort(pkg.TestGoFiles)
	slices.Sort(pkg.XTestGoFiles)
	return pkg
}

func TestCheckMissingFile(t *testing.T) {
	pkg := Package{ImportPath: "p", Dir: t.TempDir(), GoFiles: []string{"gone.go"}}
	if _, err := Check(pkg); err == nil {
		t.Fatal("expected a parse error")
	}
}

func TestViolationString(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)
	v := Violation{File: filepath.Join(dir, "a.go"), Line: 3, Message: "boom"}
	if got, want := v.String(), "a.go:3: boom"; got != want {
		t.Fatalf("got %q, want %q", got, want)
	}
	// Outside the working directory, the path stays absolute.
	v.File = filepath.Join(dir, "sub", "..", "..", "elsewhere.go")
	if got := v.String(); !strings.HasPrefix(got, string(filepath.Separator)) {
		t.Fatalf("got %q, want an absolute path", got)
	}
}

func TestReceiverTypeName(t *testing.T) {
	cases := []struct {
		src  string
		want string
	}{
		{"func (f Foo) M() {}", "Foo"},
		{"func (f *Foo) M() {}", "Foo"},
		{"func (f Foo[T]) M() {}", "Foo"},
		{"func (f Foo[T, U]) M() {}", "Foo"},
		{"func (f pkg.Foo) M() {}", ""},
	}
	for _, c := range cases {
		fset := token.NewFileSet()
		f, err := parser.ParseFile(fset, "a.go", "package p\n\n"+c.src, parser.ParseComments)
		if err != nil {
			t.Fatal(err)
		}
		var got string
		for _, d := range f.Decls {
			if fn, ok := d.(*ast.FuncDecl); ok {
				got = receiverTypeName(fn.Recv.List[0].Type)
			}
		}
		if got != c.want {
			t.Errorf("%s: got %q, want %q", c.src, got, c.want)
		}
	}
}

func TestHasBuildConstraint(t *testing.T) {
	cases := []struct {
		src  string
		want bool
	}{
		{"package p\n", false},
		{"//go:build linux\n\npackage p\n", true},
		{"// +build linux\n\npackage p\n", false},
		{"// just a comment\n\npackage p\n", false},
	}
	for _, c := range cases {
		fset := token.NewFileSet()
		f, err := parser.ParseFile(fset, "a.go", c.src, parser.ParseComments)
		if err != nil {
			t.Fatal(err)
		}
		if got := hasBuildConstraint(f); got != c.want {
			t.Errorf("%q: got %v, want %v", c.src, got, c.want)
		}
	}
}

func TestCleanPath(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if got, want := cleanPath("a.go"), filepath.Join(wd, "a.go"); got != want {
		t.Fatalf("got %q, want %q", got, want)
	}
	if got, want := cleanPath(filepath.Join(wd, "b", "..", "c.go")), filepath.Join(wd, "c.go"); got != want {
		t.Fatalf("got %q, want %q", got, want)
	}
}
