// Copyright 2026 Marc-Antoine Ruel. All Rights Reserved. Use of this
// source code is governed by the Apache v2 license that can be found in the
// LICENSE file.

package methodfilecheck

import (
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

func TestListPackages(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)
	files := map[string]string{
		"go.mod":       "module p\n\ngo 1.27\n",
		"a.go":         "package p\n",
		"a_test.go":    "package p\n",
		"a_x_test.go":  "package p_test\n",
		"sub/b.go":     "package sub\n",
		"sub/b_gen.go": "// Code generated by x DO NOT EDIT.\n\npackage sub\n",
	}
	for name, src := range files {
		path := filepath.Join(dir, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(src), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	pkgs, err := ListPackages([]string{"./..."})
	if err != nil {
		t.Fatal(err)
	}
	slices.SortFunc(pkgs, func(a, b Package) int { return strings.Compare(a.ImportPath, b.ImportPath) })
	if len(pkgs) != 2 {
		t.Fatalf("got %d packages: %v", len(pkgs), pkgs)
	}
	p := pkgs[0]
	if p.ImportPath != "p" || p.Dir != dir {
		t.Fatalf("got %+v", p)
	}
	if !slices.Equal(p.GoFiles, []string{"a.go"}) || !slices.Equal(p.TestGoFiles, []string{"a_test.go"}) || !slices.Equal(p.XTestGoFiles, []string{"a_x_test.go"}) {
		t.Fatalf("got %+v", p)
	}
	sub := pkgs[1]
	if !slices.Equal(sub.GoFiles, []string{"b.go", "b_gen.go"}) {
		t.Fatalf("go list returns generated files too: %+v", sub)
	}

	// A default pattern and a broken pattern.
	if _, err := ListPackages(nil); err != nil {
		t.Fatal(err)
	}
	if _, err := ListPackages([]string{"./nope"}); err == nil {
		t.Fatal("expected an error")
	}
}

// TestListPackagesBrokenSyntax documents that go list -json tolerates files
// that do not parse; the parse error surfaces in Check instead.
func TestListPackagesBrokenSyntax(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module p\n\ngo 1.27\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "a.go"), []byte("package p\nfunc broken( {}\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	pkgs, err := ListPackages([]string{"./..."})
	if err != nil {
		t.Fatal(err)
	}
	if len(pkgs) != 1 {
		t.Fatalf("got %+v", pkgs)
	}
	if _, err := Check(pkgs[0]); err == nil {
		t.Fatal("expected a parse error")
	}
}
