// Copyright 2026 Marc-Antoine Ruel. All Rights Reserved. Use of this
// source code is governed by the Apache v2 license that can be found in the
// LICENSE file.

package methodfilecheck

import (
	"go/ast"
	"go/parser"
	"go/token"
	"path/filepath"
	"strings"
	"testing"

	"github.com/golangci/plugin-module-register/register"
	"golang.org/x/tools/go/analysis"
)

func TestRegistered(t *testing.T) {
	newPlugin, err := register.GetPlugin("methodfilecheck")
	if err != nil {
		t.Fatal(err)
	}
	p, err := newPlugin(map[string]any{})
	if err != nil {
		t.Fatal(err)
	}
	if p.GetLoadMode() != register.LoadModeSyntax {
		t.Fatalf("got %q", p.GetLoadMode())
	}
	analyzers, err := p.BuildAnalyzers()
	if err != nil {
		t.Fatal(err)
	}
	if len(analyzers) != 1 || analyzers[0].Name != "methodfilecheck" {
		t.Fatalf("got %+v", analyzers)
	}
	if _, err := newPlugin(map[string]any{"nope": 1}); err == nil {
		t.Fatal("expected an error on unknown settings")
	}
}

func TestRunReports(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, filepath.Join(dir, "a.go"), `package p

type Foo struct{}

func helper() {}

func (f *Foo) A() {}
`, parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}
	var got []string
	pass := &analysis.Pass{
		Analyzer: &analysis.Analyzer{Name: "methodfilecheck"},
		Fset:     fset,
		Files:    []*ast.File{f},
		Report: func(d analysis.Diagnostic) {
			got = append(got, d.Message)
		},
	}
	out, err := pluginRun(pass)
	if err != nil || out != nil {
		t.Fatalf("got %v, %v", out, err)
	}
	if len(got) != 1 || !strings.Contains(got[0], "method Foo.A: type declared at line 3") {
		t.Fatalf("got %q", got)
	}
	// Generated files are not reported.
	gen, err := parser.ParseFile(fset, filepath.Join(dir, "gen.go"), `// Code generated by x DO NOT EDIT.
package p

func (f *Foo) B() {}
`, parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}
	got = nil
	pass.Files = []*ast.File{f, gen}
	if _, err := pluginRun(pass); err != nil {
		t.Fatal(err)
	}
	if len(got) != 1 {
		t.Fatalf("got %q", got)
	}
}
