# Copyright 2026 Marc-Antoine Ruel. All Rights Reserved. Use of this
# source code is governed by the Apache v2 license that can be found in the
# LICENSE file.

# Run tests and linters on main and release changes, pull requests, and automation requests.

on:
  push:
    branches: [main, "v*"]
  pull_request:
    branches: [main, "v*"]
  workflow_dispatch:
name: Run tests
jobs:
  test:
    name: "test"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: "Check: go test -race"
        run: go test -timeout=600s -race ./...
      - name: "Check: tree is clean"
        if: always()
        run: |
          # Nothing should have changed in the tree up to that point and no
          # unsuspected file was created.
          TOUCHED=$(git status --porcelain)
          if ! test -z "$TOUCHED"; then
            echo "Oops, something touched these files, please cleanup:"
            echo "$TOUCHED"
            git diff
            false
          fi

  lint:
    name: "lint"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: "Check: lint; golangci-lint with the methodfilecheck plugin"
        run: make lint
      - name: "Check: formatting; gofmt, goimports"
        run: make format-check
      - name: "Check: go mod tidy doesn't modify files"
        run: |
          go mod tidy
          TOUCHED=$(git status --porcelain)
          if ! test -z "$TOUCHED"; then
            echo "go mod tidy was not clean, please update:"
            git diff
            false
          fi

  codeql:
    name: "codeql"
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - uses: github/codeql-action/init@v4
        with:
          languages: go
      - uses: github/codeql-action/autobuild@v4
      - uses: github/codeql-action/analyze@v4
